### PR TITLE
Change the compound score threshold from 1000 to 9000

### PR DESCRIPTION
**Pull request by skywind3000**
It is easy to exceed 1000. After working on PowerShell with z.ps for three days, I have collected 85 paths and the total score exceeded 1000 twice.

And I checked z.sh and found that:

```awk
                if( count > 9000 ) {
                    # aging
                    for( x in rank ) print x "|" 0.99*rank[x] "|" time[x]
                } else for( x in rank ) print x "|" rank[x] "|" time[x]
```

So I made this change to make aging threshold more sane.

### CODE REVIEW

**Comment by JannesMeyer** [comment]
Sounds good, but please keep in mind that I squashed your previous pull request into a single commit. So remember to pull changes from this repository before making a pull request.

**Comment by skywind3000** [comment]
Sorry about that, I will take care.

**Comment by skywind3000** [comment]
Sorry about that, I will take care.

**Comment by JannesMeyer** [comment]
Don't worry! It's already squashed and merged. Only the github UI looks weird because it shows too many commits as part of the pull request

**Pull request merged**
